### ISSUE TITLE
Favor *active* torrents over total torrents, when available

### ISSUE THREAD

**Issue by virtuallyvlad** [HDVinnie/Private-Trackers-Spreadsheet#140]
Currently, the spreadsheet has a "Torrents" column that is described as "The amount of torrents said site has".  Going by the numbers, this seems to be "total" torrents, not active.  I think instead this field should ideally be *active* torrents, not total (active + inactive), because most people do not care about dead/inactive torrents, nor should they contribute to the site's torrent count.

This issue becomes apparent when you look at two examples such as IPTorrents and TorrentLeech.  As of 2023-08-08, IPTorrents has 997,901 active torrents (of an unknown amount of total torrents), while TorrentLeech only has 543,253 active torrents (of 1,920,581 total torrents).  If you went by the spreadsheet, you'd think TL was much bigger (it currently says IPT has 1,112,764 and TL has 1,756,867).  But you'd be wrong, as when you actually go to search these sites you quickly realize IPT's collection is actually the one that is much bigger.

So I think this column should ideally show active torrents.  And maybe have an "(A)" or a "(T)" after the value to indicate which is being quoted.

**Comment by HDVinnie** [comment]
> Currently, the spreadsheet has a "Torrents" column that is described as "The amount of torrents said site has". Going by the numbers, this seems to be "total" torrents, not active. I think instead this field should ideally be _active_ torrents, not total (active + inactive), because most people do not care about dead/inactive torrents, nor should they contribute to the site's torrent count.
> 
> This issue becomes apparent when you look at two examples such as IPTorrents and TorrentLeech. As of 2023-08-08, IPTorrents has 997,901 active torrents (of an unknown amount of total torrents), while TorrentLeech only has 543,253 active torrents (of 1,920,581 total torrents). If you went by the spreadsheet, you'd think TL was much bigger (it currently says IPT has 1,112,764 and TL has 1,756,867). But you'd be wrong, as when you actually go to search these sites you quickly realize IPT's collection is actually the one that is much bigger.
> 
> So I think this column should ideally show active torrents. And maybe have an "(A)" or a "(T)" after the value to indicate which is being quoted.

@virtuallyvlad hows this look....that way users can gauge active vs dead which can say a lot about a tracker.
<img width="1440" alt="Screen Shot 2023-08-30 at 4 56 37 PM" src="https://github.com/HDVinnie/Private-Trackers-Spreadsheet/assets/12850699/4b00a534-0b24-4a0b-a600-5c41f595672c">

**Comment by virtuallyvlad** [comment]
> > Currently, the spreadsheet has a "Torrents" column that is described as "The amount of torrents said site has". Going by the numbers, this seems to be "total" torrents, not active. I think instead this field should ideally be _active_ torrents, not total (active + inactive), because most people do not care about dead/inactive torrents, nor should they contribute to the site's torrent count.
> > This issue becomes apparent when you look at two examples such as IPTorrents and TorrentLeech. As of 2023-08-08, IPTorrents has 997,901 active torrents (of an unknown amount of total torrents), while TorrentLeech only has 543,253 active torrents (of 1,920,581 total torrents). If you went by the spreadsheet, you'd think TL was much bigger (it currently says IPT has 1,112,764 and TL has 1,756,867). But you'd be wrong, as when you actually go to search these sites you quickly realize IPT's collection is actually the one that is much bigger.
> > So I think this column should ideally show active torrents. And maybe have an "(A)" or a "(T)" after the value to indicate which is being quoted.
> 
> @virtuallyvlad hows this look....that way users can gauge active vs dead which can say a lot about a tracker. <img alt="Screen Shot 2023-08-30 at 4 56 37 PM" width="1440" src="https://user-images.githubusercontent.com/12850699/264472263-4b00a534-0b24-4a0b-a600-5c41f595672c.png">

I don't know how much the active:dead ratio really says about a site.  Take TorrentLeech, which had 543K active and 1.4M dead.  You may think that's a pretty lousy ratio but people seem to like TL and recommend others join.  So I wouldn't allocate the space to a 'Dead Torrents' column if it was always visible/shown on the spreadsheet.  Now, if you had functionality for hidden columns that the user could show/display by choice, then yes there'd be no harm in adding an extra hidden-by-default column.

**Comment by virtuallyvlad** [comment]
So for the record, this suggestion ended up being declined/not implemented.  The torrent count remains as the "total" count (active + dead), which may cause certain trackers' collection sizes to appear larger than they actually are.
