### ISSUE TITLE
TorrentBD is listed as invite only on their website

### ISSUE THREAD

**Issue by qwuzzy** [HDVinnie/Private-Trackers-Spreadsheet#142]
Don't think I should link the URL here but here's a screenshot.
![brave_JAbhw0QQku](https://github.com/HDVinnie/Private-Trackers-Spreadsheet/assets/32120669/d0fcc6b7-5483-431c-b97d-a2f400534bd2)

**Comment by xzi** [comment]
Done

https://github.com/HDVinnie/Private-Trackers-Spreadsheet/pull/144
