### ISSUE TITLE
ST-Tracker shut down

### ISSUE THREAD

**Issue by inter5tella** [HDVinnie/Private-Trackers-Spreadsheet#164]
ST-Tracker has been shut down at the end of august '24 and the website is no longer available.

**Comment by nafanz** [comment]
I think it would be better if you add a link to this news. A quick search has not yielded any results on this matter yet.

You can also create a pull request to remove it from the list yourself.

**Comment by inter5tella** [comment]
This was the site of the tracker: https://st-tracker.eu/

Unfortunately, I can't provide a link to the news because it was only posted on the site itself 1 month before the shut down.
My Git knowledges are far from usable, therefore I don't really know how to request a pull.
