### ISSUE TITLE
Cell Text Color

### ISSUE THREAD

**Issue by HDVinnie** [HDVinnie/Private-Trackers-Spreadsheet#22]
I think it would be nice to add text color to cell data for `Ratio Diff` and `Join Diff`.

So if cell `data === 'Easy'` then append `text-success` class.
If cell `data === 'Medium'` then append `text-warning` class.
If cell `data === 'Hard'` then append `text-danger` class.

Thoughts?

**Comment by nafanz** [comment]
@HDVinnie 
I like the idea, but can look away `Badge`, `Tag` or `Label`?
Not sure how they are called correctly.

https://getbootstrap.com/docs/4.4/components/badge/
https://mdbootstrap.com/docs/jquery/components/badges/
https://www.datatables.net/forums/discussion/50876/
https://stackoverflow.com/questions/51314170/adding-badge-and-styling-columns-on-datatables

In addition to these columns, you can also visually divide `Type`, `Join` and `Updated`.

* `Type` and `Join` - visual separation `Music`, `TV` and other
As I understand it, this will require a change in the data format, for something like.
`"Type": "Music/TV"` > `"Type": [Music, TV]`
* `Updated` - if the last update was more than a year ago, highlight it in red.

**Comment by HDVinnie** [comment]
@nafanz look better?

**Comment by nafanz** [comment]
@HDVinnie yes.

**Comment by MrGrayOrig** [comment]
Looks Nice. @HDVinnie

**Comment by HDVinnie** [comment]
To much?

[![Screen-Shot-2020-01-11-at-12-03-50-PM.png](https://i.postimg.cc/HszQB3Yf/Screen-Shot-2020-01-11-at-12-03-50-PM.png)](https://postimg.cc/KRKkYPgN)

**Comment by nafanz** [comment]
@HDVinnie 
`Ratio` I think it does not need additional focus.
`Points` you can focus only on `Yes`, on `No` it is superfluous.

**Comment by HDVinnie** [comment]
[![Image from Gyazo](https://i.gyazo.com/8fb7f2c1f422e57cfef6374396528ca7.gif)](https://gyazo.com/8fb7f2c1f422e57cfef6374396528ca7)

A bit easier on the eyes. Thoughts?

**Comment by nafanz** [comment]
@HDVinnie 
Good, but I remain with my opinion about:
`Ratio` I think it does not need additional focus.
`Points` you can focus only on `Yes`, on `No` it is superfluous.

And `H&R` logically `Yes` should be `Red`, as a warning.
