### ISSUE TITLE
Get data from Jackett?

### ISSUE THREAD

**Issue by werrpy** [HDVinnie/Private-Trackers-Spreadsheet#58]
https://github.com/Jackett/Jackett/tree/master/src/Jackett.Common/Definitions

Before someone contributes detailed stats, could make a second table for all private trackers supported by Jackett?
For example, if we look at https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/3dtorrents.yml . We can parse the yml and get site name, private, and parse the categories to fill our type column.
`name: 3D Torrents`, `type: private`, 

```
     - {id: 14, cat: Movies, desc: "Movies XviD"}
      - {id: 34, cat: Movies, desc: "Movies UltraHD"}
      - {id: 15, cat: Movies, desc: "Movies DVD-R"}
      - {id: 11, cat: Movies, desc: "Movies 720p"}
      - {id: 13, cat: Movies, desc: "Movies 1080p"}
      - {id: 16, cat: Movies, desc: "Movies 3DTV"}
      - {id: 17, cat: Movies, desc: "Movies Blu-ray"}
      - {id: 27, cat: Movies, desc: "Movies BD25 Encode"}
      - {id: 33, cat: Movies, desc: "Movies BD9 AVCHD"}
      - {id: 22, cat: Movies, desc: "Movies 2D to 3D Conv"}
      - {id: 32, cat: Movies, desc: "Bluray MKV Remux"}
      - {id: 23, cat: Movies, desc: "Movies Evo 3D"}
      - {id: 21, cat: PC, desc: "3D Software"}
      - {id: 2, cat: Audio, desc: "Music"}
      - {id: 28, cat: XXX, desc: "Adult 720p"}
      - {id: 29, cat: XXX, desc: "Adult 1080p"}
      - {id: 30, cat: XXX, desc: "Adult Blu-ray"}
      - {id: 31, cat: Other, desc: "Misc"}
      - {id: 19, cat: Audio, desc: "Audio Packs"}
```
From this we can get, `Type: Movies, PC, Audio, XXX`

Make a second table, maybe hidden by an accordion, with headers: Name, and Type

Thoughts?

**Comment by werrpy** [comment]
Also need to parse the indexers:

https://github.com/Jackett/Jackett/tree/master/src/Jackett.Common/Indexers

For `name` and `description`, parse the class definition. For example:
```
public Pier720(IIndexerConfigurationService configService, WebClient wc, Logger l, IProtectionService ps)
            : base(name: "720pier",
                   description: "720pier is a RUSSIAN Private Torrent Tracker for HD SPORTS",
```

To fill out `type` column, search for all `AddCategoryMapping` methods

search for `TorznabCatType` for more categories (`type` column)
For example get,
`TorznabCatType.TVSport`

**Comment by HDVinnie** [comment]
Merged your PR. Thanks for the contribution @werrpy
