### ISSUE TITLE
Don't link to a god-awful and harmful website (torrentinvites)

### ISSUE THREAD

**Issue by tracker-user** [HDVinnie/Private-Trackers-Spreadsheet#84]
Hi there. I was considering to contribute to the spreadsheet until I saw that you have "torrentinvites" linked under "Other Resources" dropdown.

As someone who uses private trackers since 2009 and who spent a lot of time climbing the ladder to gain access to these private communities (by contributing to many trackers), such websites should never be referenced to, ever. I understand they might be helpful because of their "Tracker Reviews" sections, but still: you should never link to a harmful website that has "... **Buy, Trade, Sell** ... **Tracker Invites**" in the title.

The spreadsheet you made is useful for newbies or people who don't have much experience with trackers (to understand what's available). But having such a link can easily set them on the wrong path of spending money on invites and later becoming **banned for life** because they "didn't think it's forbidden":
https://www.reddit.com/r/trackers/comments/20m6ur/dont_join_forums_like_torrentinvitesorg/

I found your spreadsheet because it's listed under `r/trackers` description (largest public space for tracker discussions), so I think you should be responsible and don't help such websites as "torrentinvites" to become more popular.

If you don't think it's morally wrong to link to such websites, here're some **other reasons**:
1. The website doesn't use SSL, all pages are `http` and can be viewed/intercepted both by your ISP and by other people (if you happen to use public Wi-Fi, for example)
2. Such websites have and will be hacked: https://haveibeenpwned.com/PwnedWebsites#TorrentInvites
3. Inconsistent: if you mention one crappy website, why don't you add Torrent-Invites (with a hyphen), InviteScene, InviteHawk and so on too?

I have much respect to you for making the UNIT3D platform (used on some of my favorite trackers) and for all your other contributions. So I hope you can fix this minor issue. If people need reviews of other trackers, they can always google "PTP tracker review" and visit these websites themselves. Just please don't make them seem "respectable" in any way by having this URL under "Other Resources". They are **trash** and the fact that they happen to make reviews (with the sole purpose of buying or selling invites later) doesn't make them any better.

Looking forward to contribute and update the data **after** this issue is resolved.
I made a PR which replaces the said link with Reddit's `r/trackers` URL (much more helpful for newbies and doesn't promote invite buying/selling).

**Comment by nafanz** [comment]
I added it only because of the tracker reviews, which may be useful to a beginner.  personally, he helped me avoid a lot of useless registrations on trackers that I would never use as a result.  I did not add other similar resources, since one place is enough where reviews of trackers are posted.  if it harms the reputation of this table, let's delete it without reason.

**Comment by tracker-user** [comment]
Thanks for your consideration. Is my PR okay or should I update it by only removing the link, not replacing it?
I think mentioning the subreddit would be nice too (if someone happens to open the spreadsheet first).
