### ISSUE TITLE
Remove public trackers from the main table

### ISSUE THREAD

**Issue by tracker-user** [HDVinnie/Private-Trackers-Spreadsheet#89]
So the spreadsheet is about private trackers and the `read.js` script for parsing Jackett data has an explicit `data.type == 'private'` check (to filter public trackers).

Then maybe these public trackers should be removed since they aren't private: RuTracker, PornoLab, LostFilmTV (not even a tracker anymore).

I think only trackers that _sometimes_ have open registrations should be present in the table. There's no need to list and update data for trackers that are always open.

If you agree, I can provide a pull request.

**Comment by nafanz** [comment]
I would suggest another solution: rename the spreadsheet to "Trackers-Spreadsheet" (if this is misleading anyone).

Since information about public trackers is also useful.

**Comment by nafanz** [comment]
@tracker-user 
PornoLab and RuTracker added Arihan committed on 1 Jan 2020
https://github.com/HDVinnie/Private-Trackers-Spreadsheet/commit/81e6bd21786211fcf1647625514963658a061958

After that i decided to add LostFilmTV (committed on 9 Jan 2020)
https://github.com/HDVinnie/Private-Trackers-Spreadsheet/commit/a9966896267e17c3e538ddd4011ba9cf6b459980
It has no statistics data, these columns are empty in the table.

Why not add all public trackers?
The answer is simple: everyone adds the trackers they use and finds them useful.

In general, I think that the decision is for @HDVinnie

**Comment by HDVinnie** [comment]
This list should contain Private Trackers only.

**Comment by nafanz** [comment]
@tracker-user make PR.
