### ISSUE TITLE
Consider removing Moz Grade column

### ISSUE THREAD

**Issue by tracker-user** [HDVinnie/Private-Trackers-Spreadsheet#91]
I'm back 🙂 One more question to discuss: I see no purpose in Mozilla Observatory ratings for private trackers.

First of all, there's no way an automatic checker can access all tracker pages: it sees only the login page. How would it know if the website is safe or not? Not to mention, anyone who decides to join such private communities should understand possible risks ([more info](https://wiki.installgentoo.com/wiki/Private_trackers#How_secure.2Fsafe_are_private_trackers.3F)).

This grade is mostly useful for web developers who would like to test their own websites and learn what can be improved. There're other safety checkers like Google's [Safe Browsing](https://transparencyreport.google.com/safe-browsing/search) or [WOT Security Check](https://www.mywot.com/website-safety-check). But they are equally worthless for your average private trackers user.

Current ratings are actually **misleading**: such a respected tracker as BTN got an F (lowest score) while trackers like IPTorrents got a D+ (higher score). To quote the wiki page above:
> Red trackers are essentially shady - either the **IPT** mafia empire or other trackers run by staff known for shitty practices such as trading accounts, DDoSing other sites, encouraging pay2leech or storing passwords in plaintext

So my advice is: let's remove this column altogether. I can prepare a PR later.

**Comment by HDVinnie** [comment]
I dont want to remove this column.....it can be misleading to those that donut understand it but there is allot that do and it shows how much the devs of the site clearly don't care about there security headers.
